project_id = "skfnmdworrsqnnkepqbi"

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.geo-detect]
verify_jwt = false

[functions.rebuild-leaderboards]
verify_jwt = false

[functions.create-paystack-checkout]
verify_jwt = false

[functions.verify-paystack-payment]
verify_jwt = false

[functions.generate-question-packs]
verify_jwt = false
